name: presentation
description: A new Flutter package project.
version: 0.0.1
homepage:
publish_to: 'none'

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  get_it: ^7.6.4
  injectable: ^2.3.2

  # for state management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  # for multi language
  easy_localization: ^3.0.3
  easy_localization_loader: ^2.0.0

  # for validator
  formz: ^0.6.1

  # for widget
  flutter_svg: ^2.0.9
  # cached_network_image: ^3.3.0
  lottie: ^2.3.2
  pinput: ^3.0.1
  cached_network_image: ^3.3.1

  # for media
  # video_player: ^2.8.1

  # for checking network
  connectivity_plus: ^5.0.0

  permission_handler: ^11.0.1

  core:
    path: ../core
  domain:
    path: ../domain
  data:
    path: ../data
  environment:
    path: ../environment
  permission_lib:
    path: ../3rd_party/permission_lib

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  build_runner:
  injectable_generator:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  assets:
    - assets/images/
    - assets/icons/
    - assets/translations/
    - assets/animations/
    - assets/fonts/
    - assets/fonts/inter/
    - assets/fonts/rebond/
  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/inter/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/inter/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/inter/Inter-Bold.ttf
          weight: 700
    - family: RebondGrotesque
      fonts:
        - asset: assets/fonts/rebond/Rebond_Grotesque.otf
          weight: 400
        - asset: assets/fonts/rebond/Rebond_Grotesque-Medium.otf
          weight: 500
        - asset: assets/fonts/rebond/Rebond_Grotesque-Bold.otf
          weight: 600

  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
